name: Push
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Docker to GitHub Package Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
#      - name: Bump version and push tag
#        id: tag
#        uses: anothrNick/github-tag-action@1.17.2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
