name: Push
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Docker to GitHub Package Registry
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}/raspberrypi3-opencv
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          context: ${{ github.workspace }}
          tags: latest,${{ steps.tag.outputs.new_tag }}
          cache: true
